#Numpy library tuturiol
numpy is a general purpose array processing package.it provides a high performance multidimensional array object and tools for working with these arrays its the fundamental package for sceintific computing with python

####What is array=an array is a data structure that stores values of same data type in python .this is the main difference between arrays and lists.while python lists can contain values corresponding to different data types,arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [8]:
import numpy as np
my_list=[1,2,3,4,5]
array=np.array(my_list)
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# its inbulit function that see how many number colum and how many rows
array.shape

(5,)

In [5]:
## multinested array
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[12,13,14,15,16]
array=np.array([my_list1,my_list2,my_list3])
print(array)
array.reshape(5,3)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [12 13 14 15 16]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13],
       [14, 15, 16]])

In [17]:
array.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13],
       [14, 15, 16]])

In [18]:
#idexing:accessing array element
array=np.array([1,2,3,4,5])
print(array)
print(array[4])


[1 2 3 4 5]
5


In [54]:
#now we determine two dimensional index
my_list1=[1,2,3,4]
my_list2=[6,7,8,9]
my_list3=[2,1,4,5]
array=np.array([my_list1,my_list2,my_list3])
array.reshape(3,4)



array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [2, 1, 4, 5]])

In [89]:
#[:,:] here show that all rows and colum indexs. this is index for two dimensional
#array[:,:]
#array[0:2,0:2]
#array[1:3,2:]
#array=np.arange(0,10,step=2)here it show that start from where and end where so write it and 
                             #'step' mean bring gap in it where i use two so to gap is come
#array=np.linspace(0,10,50)seet it again to understand more

array

<function numpy.array>

In [5]:
#her we use copy() function and broadcasting =its mean forexam [1,2,3,4,5,6]and i say to you here from three
# i want that 20 is come so here the array come this type [1,2,3,20,20,20]
bro=[1,2,3,4,5,6]
bro=np.array(bro)


In [6]:
bro[3:]=20
print(bro)

[ 1  2  3 20 20 20]


In [7]:
bro1=bro
bro1[3:]=500
print(bro1)
print(bro1)

[  1   2   3 500 500 500]
[  1   2   3 500 500 500]


In [ ]:
bro1=bro.copy()

In [8]:
print(bro)
bro1[3:]=1000
print(bro1)

[  1   2   3 500 500 500]
[   1    2    3 1000 1000 1000]


In [14]:
### some conditions very useful in exploratory Data Analysis
val=2
bro[bro1<200]## what does it mean

array([1, 2, 3])

In [23]:
np.ones(4)## we write it here so in array it give me four time of ones thats the mean of that



array([1., 1., 1., 1.])

In [ ]:
np.ones(4,dtype=int)#just we want two finsh decimal in it see the above array and below array

array([1, 1, 1, 1])

In [3]:
np.ones((4,5),dtype=int)#it means we make two dimensional array in it here so (4,5) represent two rows and
                        # 5 colum

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [4]:
## random distribution
np.random.rand(3,3)

array([[0.28993249, 0.39565154, 0.87075329],
       [0.63251965, 0.08567529, 0.61572646],
       [0.89682343, 0.99772442, 0.79699122]])

In [5]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[ 0.6631526 , -2.09542949, -0.10062395,  0.39435067],
       [ 1.30998996, -0.22859156,  1.47903935,  0.03850062],
       [ 1.13461213, -0.33200153,  2.07221159,  2.21159379],
       [-0.40371682, -0.86303624,  1.93881239,  0.32057512]])

In [18]:
arr_ex=np.random.randint(0,100,8).reshape(2,4)
arr_ex

array([[26, 38,  9, 64],
       [37, 20, 71, 60]], dtype=int32)

In [23]:
arr_ex=np.random.random_sample((2,4))
arr_ex

array([[0.35832411, 0.38246215, 0.6295976 , 0.60586759],
       [0.70584664, 0.30217757, 0.69907535, 0.29448485]])